name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Workflow ini hanya akan dijalankan ketika ada perubahan pada branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Menggunakan runner berbasis Ubuntu

    steps:
    - name: Check out code
      uses: actions/checkout@v2  # Mengambil kode dari repository

    - name: Set up Node.js (optional, jika Anda ingin menjalankan aplikasi frontend berbasis JS)
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Atur versi Node.js yang sesuai jika diperlukan

    - name: Install dependencies (optional)
      run: |
        npm install  # Install dependencies, jika menggunakan npm atau yarn untuk manajemen paket

    - name: Make changes to the style
      run: |
        sed -i 's/rgb(249, 228, 255)/green/' style.css  # Mengganti background menjadi hijau di style.css

    - name: Commit changes
      run: |
        git config --global user.email "you@example.com"  # Ganti dengan email Anda
        git config --global user.name "Your Name"  # Ganti dengan nama Anda
        git add style.css
        git commit -m "Change background to green"
        git push origin main  # Mengirimkan perubahan ke repository

