name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Pipeline berjalan setiap ada perubahan di branch `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t suit-otomatis .

      # Step 3: Login to AWS EC2 via SSH
      - name: SSH to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user  # Username Anda
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker stop suit-otomatis-container || true
            docker rm suit-otomatis-container || true
            docker run -d --name suit-otomatis-container -p 80:80 suit-otomatis
