name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Pipeline berjalan setiap ada perubahan di branch `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t suit-otomatis .

      # Step 3: Save Docker Image to tarball
      - name: Save Docker Image
        run: |
          docker save -o suit-otomatis.tar suit-otomatis

      # Step 4: Upload Docker Image Artifact
      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: suit-otomatis-image
          path: suit-otomatis.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Menunggu proses build selesai

    steps:
      # Step 1: Download Docker Image Artifact
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: suit-otomatis-image

      # Step 2: Login to AWS EC2 via SSH and Deploy Docker Container
      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user  # Username Anda
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Buat direktori untuk upload file jika belum ada
            mkdir -p ~/docker-images

            # Upload Docker image tarball ke EC2
            scp suit-otomatis.tar ec2-user@${{ secrets.EC2_PUBLIC_IP }}:~/docker-images/

            # Load Docker image di EC2
            docker load -i ~/docker-images/suit-otomatis.tar

            # Stop dan Remove container lama jika ada
            docker stop suit-otomatis-container || true
            docker rm suit-otomatis-container || true

            # Jalankan container baru
            docker run -d --name suit-otomatis-container -p 80:80 suit-otomatis
